### ISSUE TITLE
E/HMSSDK_HMSBIInitializer: Failed to get device issue country

### ISSUE THREAD

**Issue by holmio** [HMS-Core/hms-cordova-plugin#13]
**Description**
Push service can not be initialized after doing the whole configurations in AppGallery Connect.

**Expected behavior**
Push service should be initialized without errors and get token.

**Current behavior**
HMSSDK_HMSBIInitializer is throwing an error: "Failed to get device issue country". and the Push service is not working.

**Logs**
2020-11-12 15:33:54.558 2587-21545/de.example.app I/HMSSDK_HMSBIInitializer: Builder->biInitFlag :false
2020-11-12 15:33:54.559 2587-21545/de.example.app I/HMSSDK_HMSBIInitializer: Builder->biSetting :false
2020-11-12 15:33:54.559 2587-21545/de.example.app I/HMSSDK_CountryCodeBean: getCountryCode get country code from SIM_COUNTRY
2020-11-12 15:33:54.560 2587-21432/de.example.app I/hwschromium-390: [INFO:network_service_network_delegate.cc(98)] resource : https://*** error code: 403
2020-11-12 15:33:54.560 2587-21545/de.example.app W/HMSSDK_CountryCodeBean: countryCode from system language is not reliable.
2020-11-12 15:33:54.560 2587-21545/de.example.app E/HMSSDK_HMSBIInitializer: Failed to get device issue country
2020-11-12 15:33:54.560 2587-21545/de.example.app D/HMSLogger: HMS Plugin Dotting is Enabled!
2020-11-12 15:33:54.562 2587-21432/de.example.app E/hwschromium-390: [ERROR:network_service_network_delegate.cc(243)] final url https://*** error_code: -3
2020-11-12 15:33:54.566 2587-21545/de.shoop.app I/HMSPush: HMSPush initialized 

**Environment**
Ionic:

   Ionic CLI                     : 6.11.8
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1001.4
   @angular-devkit/schematics    : 10.1.4
   @angular/cli                  : 10.1.4
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-webview 5.0.0, (and 31 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.2.2)   : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/mohammdeljamami/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 12.0 Build version 12A7209

**Comment by aktug** [comment]
Hi @holmio ,
Did you set the **Data Storage Location** in [AppGallery Connect](https://developer.huawei.com/consumer/en/service/josp/agc/index.html)

**Comment by aktug** [comment]
Hi @holmio ,
Did you set the **Data Storage Location** in [AppGallery Connect](https://developer.huawei.com/consumer/en/service/josp/agc/index.html)

![image](https://user-images.githubusercontent.com/20382405/99035045-cd4f2800-258f-11eb-9fd2-7c7d96ab5a0d.png)

And what is your region/country? You can find supported locations at https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/support-regions-0000001050047520-V5

**Comment by holmio** [comment]
Yes, I did.
<img width="442" alt="Screenshot 2020-11-13 at 08 17 45" src="https://user-images.githubusercontent.com/12999579/99040174-f5875880-2588-11eb-9e32-6fc5dca827d2.png">

**Comment by fuatbakkal** [comment]
What's the model of the phone you're running? and what's country did you run your application in?

**Comment by holmio** [comment]
_Does application crashed or just not able to initialize HMS Push service?_
Not able to initialize HMS Push service.

_Did you run your application in release flavor or debug flavor?_
debug flavor

_What's the model of the phone you're running?_
HUAWEI P40 lite. JNY-LX1. EMUI Version: 10.1.0. Android 10.

_What's country did you run your application in?_
Germany and UK with VPN

**Comment by mesutgedik** [comment]
Hello,

I think your issue is not coming from "Failed to get device issue country" message. You can get a token even if you get this error. Please try this options below one by one to obtain a token. If these steps not help to you please contact again.

First Option: Add  <meta-data android:name="push_kit_auto_init_enabled" android:value="true" /> to AndroidManifest.xml for automatic initialization and get a token.

Second Option: Call setAutoInitEnabled(true) method to enable automatic initialization and get a token. 

Third Option: Call getToken() method to obtain a token.

**Comment by holmio** [comment]
It works. Thanks for the help 👍🏼 !!
But, it looks like `setAutoInitEnabled(true)` is required, at least in Cordova projects.
And I don't understand why you have two methods to initialize the push service.

**Comment by mesutgedik** [comment]
We don't have two methods to initialize push service. When you add push plugin to application and the application opened successfully you can see the **"HmsPush initialized"** in logcat. This log shows you, Hms Push plugin correctly added and working on  the project. But you need to obtain a token to use push services. So that you need these options to obtain a token, not to initialize it.

`setAutoInitEnabled` method sets whether to enable automatic initialization . If this parameter is set to true, the SDK automatically generates an AAID and applies for a token. The token is returned through the `HmsPushEvent.onTokenReceived()` callback method.
